#!/bin/sh

set -e

if [ ! -f /opt/homebrew/bin/brew ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    install
fi

if [ ! -d ~/dotfiles ]; then
    cd ~
    git clone https://github.com/nao-18/dotfiles.git
fi

# if [ ! -d /opt/homebrew/bin/yabai ]; then
#     arch -arm64 brew install yabai
# fi

# if [ ! -d /opt/homebrew/bin/skhd ]; then
#     arch -arm64 brew install skhd
# fi

brew bundle -v --file=~/dotfiles/Brewfile

if [ ! -d ~/.config ]; then
    mkdir ~/.config
fi
stow -v -d ~/dotfiles/packages -t ~ zsh starship